package com.engine.dzapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.engine.dzapp.dao.UserTable;
import com.engine.dzapp.dao.Event;

import com.engine.dzapp.dao.UserTableDao;
import com.engine.dzapp.dao.EventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userTableDaoConfig;
    private final DaoConfig eventDaoConfig;

    private final UserTableDao userTableDao;
    private final EventDao eventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userTableDaoConfig = daoConfigMap.get(UserTableDao.class).clone();
        userTableDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        userTableDao = new UserTableDao(userTableDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);

        registerDao(UserTable.class, userTableDao);
        registerDao(Event.class, eventDao);
    }
    
    public void clear() {
        userTableDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
    }

    public UserTableDao getUserTableDao() {
        return userTableDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

}
