package com.engine.dzapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_TABLE.
 */
public class UserTable {

    private String userName;
    private String password;
    private Long time;

    public UserTable() {
    }

    public UserTable(String userName) {
        this.userName = userName;
    }

    public UserTable(String userName, String password, Long time) {
        this.userName = userName;
        this.password = password;
        this.time = time;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
